export * from './categoria.interface'
export * from './encargado.interface'
export * from './ingredientes.interface'
export * from './menu-plato.interface'
export * from './menu.interface'
export * from './plato.interface'
export * from './receta-ingredientes.interface'
export * from './receta.interface'